---
ID: "bfa3dc68-27d1-4e80-ab6c-246158e98102"
Parent: "4eec9461-e26d-4a19-a59f-6d973a128b0b"
Template: "4eec9461-e26d-4a19-a59f-6d973a128b0b"
Path: /sitecore/templates/Data Exchange/Providers/JSON/Folders/JSON Value Readers Root/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200215T162438Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
