---
ID: "61c3a80b-0a05-480b-90e5-14b0b15a6e2d"
Parent: "2a468299-1262-4c53-8a77-3df205d1e05f"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Data Exchange/Providers/JSON/Data Access/Value Readers/Composite Value Reader/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200216T231855Z
