---
ID: "bb4c2ac3-9bf4-47d6-ba92-815de8829b6f"
Parent: "7c958233-3458-46b2-be59-8a47271a0289"
Template: "7402adfe-48cf-4bb2-9203-d4d95ade709e"
Path: /sitecore/system/Data Exchange/Blog Tenant/Tenant Service Settings
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 425
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200222T184907Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
