---
ID: "7f5e849d-16d4-40fa-81c9-aad480f65c5a"
Parent: "e745798c-2af9-4be9-b874-46106db16adf"
Template: "e745798c-2af9-4be9-b874-46106db16adf"
Path: /sitecore/templates/Data Exchange/Providers/JSON/Folders/JSON Endpoints Root/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200215T162438Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
