---
ID: "0fcac432-d1e3-4658-b27b-465f5007ae0b"
Parent: "8a6a1293-7166-4455-b12b-379eb3b81edb"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Data Exchange/Providers/JSON/Data Access/Value Readers/JSON Value Reader/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200208T185907Z
