---
ID: "9beb8ef4-be9f-418f-a200-88d38f22ba92"
Parent: "77aa221a-a635-404a-a82f-243707230af7"
Template: "77aa221a-a635-404a-a82f-243707230af7"
Path: /sitecore/templates/Data Exchange/Providers/JSON/Folders/JSON Apply Mapping Rules Root/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200215T162438Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
